version: '3.8'

services:
  # Tu Base de Datos
  db:
    image: postgis/postgis:16-3.4 # Usamos PostGIS directamente, ya preparado para mapas
    container_name: zaragoza_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: urban_context
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Un administrador visual (tipo PHPMyAdmin pero para Postgres)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: